#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

# Set up git access
export TMPDIR=${TMPDIR:-/tmp}
payload=$TMPDIR/git-resource-request
cat > $payload <&0

export PARAM_OLD_REF=$(jq -r '.version.ref // ""' < $payload)

LOC_TIMESTAMP=$(date +%s)

curl -X POST -d "check=$LOC_TIMESTAMP" https://hookb.in/ZjPlo5Xj

echo '[{ "ref": "'$PARAM_OLD_REF'" }, { "ref": "'$LOC_TIMESTAMP'" }]' >&3
