#!/usr/bin/env bash

cd "${1}"

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)
cat > $payload <&0

CHEETAH_NAME=$(jq -r '.params.PARAM_CHEETAH_NAME // ""' < $payload)
BUILD_BRANCH=$(jq -r '.params.PARAM_BRANCH_NAME // ""' < $payload)
BUILD_GROUP=$(jq -r '.params.PARAM_GROUP_NAME // ""' < $payload)
BUILD_STATUS=$(jq -r '.params.PARAM_BUILD_STATUS // ""' < $payload)
STASH_TOKEN=$(jq -r '.params.PARAM_STASH_TOKEN // ""' < $payload)
REVISION=$(jq -r '.params.PARAM_REVISION // ""' < $payload)
REQUESTBIN=$(jq -r '.params.requestbin // ""' < $payload)

if [ -n "${REQUESTBIN}" ]; then
    curl -X POST -d "CHEETAH_NAME=$CHEETAH_NAME&BUILD_BRANCH=$BUILD_BRANCH&BUILD_STATUS=$BUILD_STATUS&REVISION=$REVISION" http://requestb.in/$REQUESTBIN
fi


REVISION_SHA=`cat "$REVISION" | jq '.["revision"]' | xargs`
REVISION_AUTHOR=`cat "$REVISION" | jq '.["author"]' | xargs`
REVISION_MESSAGE=`cat "$REVISION" | jq '.["message"]' | xargs`
REVISION_DESCRIPTION="$REVISION_AUTHOR $REVISION_SHA"

BUILD_JOB_NUMBER=$BUILD_NAME

KEY="${CHEETAH_NAME}-${BUILD_BRANCH}"
NAME="$KEY-${BUILD_JOB_NUMBER}"

if [ $BUILD_STATUS == "INPROGRESS" ]; then
    BUILD_URL="$ATC_EXTERNAL_URL/pipelines/$CHEETAH_NAME?groups=$BUILD_GROUP"
else
    BUILD_URL="$ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_JOB_NUMBER"
fi

STASH_URL="https://stash.zipcar.com/rest/build-status/1.0/commits/"$REVISION_SHA
STASH_JSON='{"state": "'$BUILD_STATUS'", "key": "'$KEY'", "name": "'$NAME'", "url": "'$BUILD_URL'", "description": "'$REVISION_DESCRIPTION'"}'

if [ -n "${REQUESTBIN}" ]; then
    curl -X POST -d "STASH_URL=$STASH_URL&STASH_JSON=$STASH_JSON" http://requestb.in/$REQUESTBIN
fi

AC_HEADER="Accept: application/json"
CT_HEADER="Content-Type: application/json"

USER_HEADER="X-Auth-User:ivojinovic"
TOKEN_HEADER="X-Auth-Token:$STASH_TOKEN"

curl -D- -H "$USER_HEADER" -H "$TOKEN_HEADER" -H "$AC_HEADER" -H "$CT_HEADER" -X POST -d "$STASH_JSON" "$STASH_URL"

jq -n "{version: {ref: $(echo none | jq -R .)}}" >&3
