#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "${payload}" <&0

concourse_url="$(jq -r '.source.concourse_url' < "${payload}")"

curl -X POST -d "concourse_url=$concourse_url" http://requestb.in/14i248t1?inspect
